spring:
  application:
    name: kafka-camel-router

# Camel Configuration
camel:
  springboot:
    name: OrderRoutingApplication
  component:
    kafka:
      brokers: localhost:9092

logging:
  level:
    com.example.kafkarouter: DEBUG
    org.apache.camel: INFO
    org.apache.kafka: INFO